version: "3"
services:

  jenkins:
    container_name: jenkins-container
    build:
      context: .
      dockerfile: ./Dockerfile_Jenkins
      args:
        JENKINS_USER_ADMIN_PASSWORD: ${JENKINS_USER_ADMIN_PASSWORD}
        JENKINS_USER_DEVELOPER_PASSWORD: ${JENKINS_USER_DEVELOPER_PASSWORD}
        JENKINS_RS_PATH: ${JENKINS_RS_PATH}
        JENKINS_URL: ${JENKINS_URL}
        SSH_AGENT_PRIVATE_KEY_FILE: ${SSH_AGENT_PRIVATE_KEY_FILE}
    ports:
      - "8080:8080"
    image: outside-jenkins
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    extra_hosts:
      - "localhost:host-gateway"
    restart: always

  static-agent:
    container_name: static-agent-container
    build:
      context: .
      dockerfile: ./Dockerfile_JenkinsAgent
      args:
        JENKINS_RS_PATH: ${JENKINS_RS_PATH}
        SSH_AGENT_PUBLIC_KEY_FILE: ${SSH_AGENT_PUBLIC_KEY_FILE}
        HOST_DOCKER_GUID: ${HOST_DOCKER_GUID}
    ports:
      - "24:22"
    image: outside-jenkins-static-agent
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    extra_hosts:
      - "localhost:host-gateway"
    restart: always