jenkins:
  systemMessage: "Outside Jenkins"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "administrator"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "dev"
            description: "developer"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
              - "Job/Workspace"
              - "Agent/Build"
            assignments:
              - "developer"
  noUsageStatistics: true
  nodes:
    - permanent:
        name: "jenkins-agent1"
        remoteFS: "/home/jenkins"
        numExecutors: 1
        launcher:
          ssh:
            host: "static-agent"
            port: 22
            javaPath: "/opt/jdk-17/bin/java"
            credentialsId: jenkins
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "administrator"
          password: ${JENKINS_USER_ADMIN_PASSWORD}
        - id: "developer"
          name: "dev"
          password: ${JENKINS_USER_DEVELOPER_PASSWORD}

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: "TriggeringUsersAuthorizationStrategy"

unclassified:
  location:
    url: ${JENKINS_URL}

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: jenkins
              username: jenkins
              description: "Jenkins agent ssh private key."
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_AGENT_PRIVATE_KEY_FILE}}"

jobs:
  - file: /usr/local/jobs.groovy