FROM jenkins/jenkins@sha256:ea48cb1a1bb0acd1e947fcfc84dc97c203ed42db9c012dc932b3c9eacc190d70

SHELL ["/bin/bash", "-c"]

ARG JENKINS_USER_ADMIN_PASSWORD \
    JENKINS_USER_DEVELOPER_PASSWORD \
    JENKINS_RESOURCES_PATH \
    JENKINS_URL \
    SSH_AGENT_PRIVATE_KEY_FILE


# Jenkins configuration
COPY ${SSH_AGENT_PRIVATE_KEY_FILE} /etc/.ssh/jenkins-agent-key
USER root
RUN chown jenkins /etc/.ssh/jenkins-agent-key
RUN chmod 600 /etc/.ssh/jenkins-agent-key
USER jenkins

COPY ${JENKINS_RESOURCES_PATH}/plugins.txt /usr/local/plugins.txt
COPY ${JENKINS_RESOURCES_PATH}/configuration.yml /usr/local/configuration.yml
COPY ${JENKINS_RESOURCES_PATH}/jobs.groovy  /usr/local/jobs.groovy
COPY ${JENKINS_RESOURCES_PATH}/Jenkinsfile  /usr/local/Jenkinsfile

RUN /usr/local/bin/install-plugins.sh < /usr/local/plugins.txt

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /usr/local/configuration.yml
ENV JENKINS_USER_ADMIN_PASSWORD $JENKINS_USER_ADMIN_PASSWORD
ENV JENKINS_USER_DEVELOPER_PASSWORD $JENKINS_USER_DEVELOPER_PASSWORD
ENV JENKINS_URL $JENKINS_URL
ENV SSH_AGENT_PRIVATE_KEY_FILE /etc/.ssh/jenkins-agent-key
# ----------