pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -f ./Dockerfile .'
            }
        }
        stage('Unit Test') {
            steps {
               sh 'docker build -f ./Dockerfile .'
               sh 'env'
            }
        }
    }
    post {
        always {
            emailext (
                to: '$DEFAULT_RECIPIENTS',
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT'
            )

            discordSend (
                webhookURL: "${DISCORD_WEBHOOK_URL}",
                title: "${JOB_NAME} #${BUILD_NUMBER}",
                description: "Build: ${BUILD_NUMBER}\nStatus: ${currentBuild.currentResult.toLowerCase()}",
                footer: "Build Duration: ${currentBuild.durationString}",
                result: currentBuild.currentResult,
                link: BUILD_URL,
            )
        }
    }
}